version: '1'

services:

  postgres:
    container_name: pg
    image: postgres:15.2
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT_OUTSIDE}:${POSTGRES_PORT_INSIDE}


  postgres_test:
    container_name: pg-test
    image: postgres:15.2
    restart: always
    profiles:
      - test
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    hostname: postgres
    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT_OUTSIDE}:${POSTGRES_PORT_INSIDE}

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    hostname: rabbitmq
    restart: always
    env_file:
      - ./.env
    ports:
      - ${RABBITMQ_PORT_OUTSIDE}:${RABBITMQ_PORT_INSIDE}

  access:
    container_name: access
    build:
      context: ./
      dockerfile: ./access-service/Dockerfile
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
    volumes:
      - ./access-service:/access-service
      - /app/node_modules

  datas:
    container_name: datas
    build:
      context: ./
      dockerfile: ./data-service/Dockerfile
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
    volumes:
      - ./data-service:/data-service
      - /app/node_modules

  main:
    container_name: main
    build: 
      context: ./
      dockerfile: ./main-module/Dockerfile
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
      - access
      - datas
    volumes:
      - ./main-module:/main-module
      - /app/node_modules
    ports:
      - ${OUTSIDE_PORT}:${INSIDE_PORT}